name: "Run Verification Tests"
description: "Run coherency tests including bundle size analysis with Bun"

inputs:
  build-artifact:
    description: "Name of the build artifact to download"
    required: true

outputs:
  status:
    description: "Verification test execution status"
    value: ${{ steps.coherency.outputs.status }}

  details:
    description: "Verification test execution details"
    value: ${{ steps.coherency.outputs.details }}

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact }}
        path: build/

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      shell: bash
      run: bun install

    - name: Run coherency tests
      id: coherency
      shell: bash
      run: |
        echo "Running coherency tests with Bun..."

        # Run coherency script with bun run
        if bun run coherency; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "details=Coherency checks passed" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "details=Coherency issues detected" >> $GITHUB_OUTPUT
          exit 1
        fi
