name: "Release Setup"
description: "Setup environment for release workflow with GitHub App token"

inputs:
  app-id:
    description: "GitHub App ID"
    required: true

  private-key:
    description: "GitHub App private key"
    required: true

  fetch-depth:
    description: "Number of commits to fetch"
    required: false
    default: "0"

outputs:
  token:
    description: "GitHub App token"
    value: ${{ steps.get_token.outputs.token }}

runs:
  using: "composite"
  steps:
    - name: Get GitHub App Token
      id: get_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.private-key }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ steps.get_token.outputs.token }}
