name: "Checkout and Download Artifacts"
description: "Checkout code with proper ref handling and optionally download artifacts"

inputs:
  fetch-depth:
    description: "Number of commits to fetch"
    required: false
    default: "1"

  download-package:
    description: "Download package.json artifact"
    required: false
    default: "false"

  download-build:
    description: "Download build output artifact"
    required: false
    default: "false"

  artifact-package-name:
    description: "Name of the package artifact"
    required: false
    default: ""

  artifact-build-name:
    description: "Name of the build artifact"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Download package.json artifact
      if: inputs.download-package == 'true' && inputs.artifact-package-name != ''
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-package-name }}

    - name: Download build output artifact
      if: inputs.download-build == 'true' && inputs.artifact-build-name != ''
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-build-name }}
